const TYPE_MACHINE = Object.freeze({
	OPEN_MODAL: 'OPEN_MODAL',
	TOGGLE_SMALLER: 'TOGGLE_SMALLER',
	TOGGLE_DEFAULT: 'TOGGLE_DEFAULT',
	TOGGLE_PAUSE: 'TOGGLE_PAUSE',
	TOGGLE_PLAY: 'TOGGLE_PLAY',
	CLOSE_MODAL: 'CLOSE_MODAL',
})

export {
	TYPE_MACHINE,
}